import '../global.css'
import type { AppProps } from 'next/app'
import { Toaster } from 'react-hot-toast'
import Head from 'next/head'
import CurrentUserProvider from 'contexts/CurrentUserContext'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>The Grand Cocktail Compendium</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster position="top-right" />
      <CurrentUserProvider>
        <Component {...pageProps} />
      </CurrentUserProvider>
    </>
  )
}

export default MyApp
